# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
units: "config/units.tsv"

common:
  build: 'hg19'
  genome: '/mnt/work1/data/genomes/human/hg19/iGenomes/Sequence/WholeGenomeFasta/genome.fa'
    
gatk:
  indel_realigner_hg19:
    dbsnp: '/mnt/work1/data/genomes/human/hg19/variantcallingdata/dbsnp_138.hg19.vcf'
    1000gsnps: '/mnt/work1/data/genomes/human/hg19/variantcallingdata/1000G_phase1.snps.high_confidence.hg19.vcf'
    1000gindels: '/mnt/work1/data/genomes/human/hg19/variantcallingdata/1000G_phase1.indels.hg19.vcf'
    millsindels: '/mnt/work1/data/genomes/human/hg19/variantcallingdata/Mills_and_1000G_gold_standard.indels.hg19.vcf'
    mills1000gindels: '/mnt/work1/data/genomes/human/hg19/variantcallingdata/Mills_and_1000G_gold_standard.indels.hg19.vcf'
  indel_realigner_hg38:
    dbsnp: '/mnt/work1/data/genomes/human/hg38/hg38bundle/dbsnp_144.hg38.vcf.gz'
    1000gsnps: '/mnt/work1/data/genomes/human/hg38/hg38bundle/1000G_phase1.snps.high_confidence.hg38.vcf.gz'
    1000gindels: '/mnt/work1/data/genomes/human/hg38/hg38bundle/Homo_sapiens_assembly38.variantEvalGoldStandard.vcf.gz'
    millsindels: '/mnt/work1/data/genomes/human/hg38/hg38bundle/Homo_sapiens_assembly38.known_indels.vcf'
    mills1000gindels: '/mnt/work1/data/genomes/human/hg38/hg38bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf'
